# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"nprint": "01_fastai_image_classification.ipynb"}

modules = ["utils.py"]

doc_url = "https://pages.github.ibm.com./aicoc-ai-immersion/fastai_utils/"

git_url = "https://github.ibm.com/aicoc-ai-immersion/fastai_utils/tree/master/"

def custom_doc_links(name): return None
