# AUTOGENERATED! DO NOT EDIT! File to edit: FastAI/01_fastai_image_classification.ipynb (unless otherwise specified).

__all__ = ['nprint']

# Cell
from fastai.vision import *
from fastai.metrics import error_rate
from pathlib import Path
import os

# utility print function
def nprint(mystring) :
    print("**{}** : {}".format(sys._getframe(1).f_code.co_name,mystring))
