# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"npt": "UFA_steam_example.ipynb",
         "get_config": "UFA_steam_example.ipynb",
         "print_run": "UFA_steam_example.ipynb",
         "create_iap_data": "UFA_steam_example.ipynb",
         "iap3d": "UFA_steam_example.ipynb",
         "pio.renderers.default": "UFA_steam_example.ipynb",
         "fcnet": "UFA_steam_example.ipynb",
         "get_dataloader": "UFA_steam_example.ipynb",
         "weights_xavier": "UFA_steam_example.ipynb",
         "fit_model": "UFA_steam_example.ipynb",
         "visualize_results": "UFA_steam_example.ipynb",
         "cfg": "UFA_steam_example.ipynb",
         "iap_df": "UFA_steam_example.ipynb",
         "dl": "UFA_steam_example.ipynb",
         "iap_net": "UFA_steam_example.ipynb",
         "model_stats": "UFA_steam_example.ipynb",
         "epoch_loss": "UFA_steam_example.ipynb",
         "inference_all": "UFA_steam_example.ipynb",
         "prediction": "UFA_steam_example.ipynb",
         "example": "UFA_steam_example.ipynb",
         "traced_script_module": "UFA_steam_example.ipynb",
         "output": "UFA_steam_example.ipynb",
         "x_in": "UFA_steam_example.ipynb"}

modules = ["ufa.py"]

doc_url = "https://pages.github.ibm.com./aicoc-ai-immersion/py_aicoc/"

git_url = "https://github.ibm.com/aicoc-ai-immersion/py_aicoc/tree/master/"

def custom_doc_links(name): return None
