# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"xt": "Pytorch_using_CIFAR10.ipynb",
         "xt_test": "Pytorch_using_CIFAR10.ipynb",
         "train_set": "Pytorch_using_CIFAR10.ipynb",
         "test_set": "Pytorch_using_CIFAR10.ipynb",
         "batch_size": "Pytorch_using_CIFAR10.ipynb",
         "train_loader": "Pytorch_using_CIFAR10.ipynb",
         "test_loader": "Pytorch_using_CIFAR10.ipynb",
         "labels_map": "Pytorch_using_CIFAR10.ipynb",
         "NetCNN3L": "Pytorch_using_CIFAR10.ipynb",
         "model_summary": "Pytorch_using_CIFAR10.ipynb",
         "weights_uniform_random": "Pytorch_using_CIFAR10.ipynb",
         "weights_xavier": "Pytorch_using_CIFAR10.ipynb",
         "train_test": "Pytorch_using_CIFAR10.ipynb",
         "curves": "Pytorch_using_CIFAR10.ipynb",
         "reset_weights": "Pytorch_using_CIFAR10.ipynb",
         "model": "Pytorch_using_CIFAR10.ipynb",
         "use_cuda": "Pytorch_using_CIFAR10.ipynb",
         "optimizer": "Pytorch_using_CIFAR10.ipynb",
         "criterion": "Pytorch_using_CIFAR10.ipynb",
         "EPOCHS": "Pytorch_using_CIFAR10.ipynb",
         "accuracy": "cifar_utils.ipynb",
         "viz_network": "cifar_utils.ipynb"}

modules = ["pytorch_cifar.py",
           "cifar_utils.py"]

doc_url = "https://pages.github.ibm.com./aicoc-ai-immersion/py_aicoc/"

git_url = "https://github.ibm.com/aicoc-ai-immersion/py_aicoc/tree/master/"

def custom_doc_links(name): return None
